services:
  - type: web
    name: doctoralis
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn postgraduation.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DEMO_MODE
        value: "True"
      - key: WEB_CONCURRENCY
        value: "2"
